include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    always_use_package_imports: false
    avoid_relative_lib_imports: false
    prefer_relative_imports: true

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
